repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version
    rev: v0.6.0
    hooks:
      # Run the linter and auto-fix errors (like unused imports)
      - id: ruff
        args: [ --fix ]
      # Run the formatter to enforce code style
      - id: ruff-format
