"""Informative test that detects changes to the public API surface.

Loads ``api_snapshot.json`` (generated by ``scripts/update_api_snapshot.py``),
computes the *current* surface from ``lughus.__all__``, and prints a clear
diff when they diverge.  The test always **passes** -- its purpose is
visibility in PR diffs, not gate-keeping.
"""

from __future__ import annotations

import json
import warnings
from pathlib import Path

import pytest

# Re-use the same collection logic the snapshot script uses so the
# comparison is apples-to-apples.
from scripts.update_api_snapshot import collect_api_surface

_SNAPSHOT_PATH = Path(__file__).resolve().parent.parent / "api_snapshot.json"


def _index_by_name(
    entries: list[dict[str, object]],
) -> dict[str, dict[str, object]]:
    return {e["name"]: e for e in entries}  # type: ignore[index]


# ---------------------------------------------------------------------------


@pytest.mark.informative
def test_api_surface_matches_snapshot() -> None:
    """Compare the live API surface against the committed snapshot."""

    if not _SNAPSHOT_PATH.exists():
        warnings.warn(
            "api_snapshot.json not found -- run "
            "'python scripts/update_api_snapshot.py' to create it.",
            stacklevel=1,
        )
        return

    snapshot_entries: list[dict[str, object]] = json.loads(
        _SNAPSHOT_PATH.read_text(encoding="utf-8"),
    )
    current_entries = collect_api_surface()

    snapshot_idx = _index_by_name(snapshot_entries)
    current_idx = _index_by_name(current_entries)

    snapshot_names = set(snapshot_idx)
    current_names = set(current_idx)

    added = sorted(current_names - snapshot_names)
    removed = sorted(snapshot_names - current_names)
    common = sorted(snapshot_names & current_names)

    changed: list[str] = []
    for name in common:
        if snapshot_idx[name] != current_idx[name]:
            changed.append(name)

    if not added and not removed and not changed:
        return  # surfaces match -- nothing to report

    # Build a human-readable report.
    lines: list[str] = [
        "",
        "=" * 60,
        "  API SURFACE CHANGE DETECTED",
        "=" * 60,
    ]

    if added:
        lines.append("")
        lines.append(f"  ADDED ({len(added)}):")
        for name in added:
            entry = current_idx[name]
            lines.append(f"    + {name}  (kind={entry.get('kind')})")

    if removed:
        lines.append("")
        lines.append(f"  REMOVED ({len(removed)}):")
        for name in removed:
            entry = snapshot_idx[name]
            lines.append(f"    - {name}  (kind={entry.get('kind')})")

    if changed:
        lines.append("")
        lines.append(f"  CHANGED ({len(changed)}):")
        for name in changed:
            lines.append(f"    ~ {name}")
            lines.append(f"        snapshot: {json.dumps(snapshot_idx[name], sort_keys=True)}")
            lines.append(f"        current:  {json.dumps(current_idx[name], sort_keys=True)}")

    lines.append("")
    lines.append(
        "  Run 'python scripts/update_api_snapshot.py' to accept these changes."
    )
    lines.append("=" * 60)

    report = "\n".join(lines)

    # Emit as a warning so it surfaces in pytest output without failing.
    warnings.warn(report, UserWarning, stacklevel=1)
