"""Canonical default values for tool execution limits.

Single source of truth imported by both BaseSettings and ToolExecutionConfig.
"""

DEFAULT_MAX_ITERATIONS = 12
DEFAULT_MAX_PARALLEL_TOOLS = 4
DEFAULT_MAX_GLOBAL_TOOLS = 64
DEFAULT_MAX_TOOL_ARGS_CHARS = 20_000
DEFAULT_MAX_TOOL_OUTPUT_CHARS = 8_192
DEFAULT_MAX_SYNC_THREAD_WORKERS = 32
DEFAULT_MAX_CONTEXT_TOKENS = 8_192
DEFAULT_TOOL_QUEUE_TIMEOUT = 30.0
DEFAULT_ARTIFACT_PROJECTION_THRESHOLD = 4096
